## Numpy와 닮은 파이토치

In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))  # 모두 정수형으로 구성됨
print(a.dtype)
print(a.shape)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])


In [3]:
b = torch.tensor([1, 2, 3.1, 4])
print(b)
print(type(b))  # 하나라도 실수면 모두 실수 타입
print(b.dtype)
print(b.shape)

tensor([1.0000, 2.0000, 3.1000, 4.0000])
<class 'torch.Tensor'>
torch.float32
torch.Size([4])


In [4]:
A = torch.tensor([[1, 2, 5], [3, 4, 5]])
print(A)
print(type(A))
print(A.dtype)
print(A.ndim)  # 차원 수
print(A.shape)  # 행렬 형태
print(A.size())  # shape
print(A.numel())  # 전체 성분 수

tensor([[1, 2, 5],
        [3, 4, 5]])
<class 'torch.Tensor'>
torch.int64
2
torch.Size([2, 3])
torch.Size([2, 3])
6


In [5]:
print(torch.zeros(5))
print(torch.zeros(3, 3))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.arange(3, 10, 2))
print(torch.arange(0, 1, 0.1))
print(torch.linspace(0, 1, 11))  # 0에서 부터 1 포함 10개로 등분

tensor([0., 0., 0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [6]:
A = torch.tensor([[1, 2, 3], [1, 2, 3]])
B = torch.tensor([[4, 5, 6], [1, 1, 1]])
print(A + B)
print(A - B)
print(A * B)  # Hadamard product
print(A / B)
print(A**2)

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])
tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[1, 4, 9],
        [1, 4, 9]])


In [7]:
print(B.T)
print(A @ B.T)  # 행렬 곱

tensor([[4, 1],
        [5, 1],
        [6, 1]])
tensor([[32,  6],
        [32,  6]])


### 다차원 행렬의 인덱싱

In [8]:
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[0, 2])  # list는 안됨
print(A[0][2])
print(A[0, 0:3:2])
print(A[:, 2])  # 2열만 가져올 수 있도록 함(list에는 없는 기능)
print(A[:][2])  # not equal to print(A[:, 2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([1, 3])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [9]:
A = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(A)
print(A.shape)
print(A[0, 1, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([2, 3, 3])
tensor(6)


### Boolean indexing

In [10]:
A = torch.tensor([[1, 2, 3, 4], [1, 2, 3, 4]])
print(A == 3)
print(A[A == 3])
A[A == 3] = 100
print(A)

tensor([[False, False,  True, False],
        [False, False,  True, False]])
tensor([3, 3])
tensor([[  1,   2, 100,   4],
        [  1,   2, 100,   4]])


In [11]:
A = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
B = torch.tensor([True, False, True, False])
print(A[B, :])  # True행만 가져옴

tensor([[1, 2],
        [5, 6]])


### Tensor indexing

In [12]:
a = torch.tensor([1, 2, 3, 4, 5])
A = a[2]
print(A)

A = a[torch.tensor(2)]
print(A)

A = a[torch.tensor([2, 3, 4])]
print(A)

A = a[torch.tensor([[2, 2, 2], [3, 3, 3]])]
print(A)  # 인덱싱된 값으로 새 행렬을 만듬

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
A = a[
    torch.tensor([[0, 1], [1, 1]])
]  # 차원이 늘어나면서 표현됨, [0]은 [1, 2, 3]을 내포함, # segmetation 결과 그룹 보여줄 때 사용함
print(A)

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [13]:
A = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
# 유형 1 : 위치
print(A)
print(A.shape)

# 유형 2 : True인 위치를 반환
print(A[torch.tensor([[False, True], [False, False], [False, False], [False, False]])])
print(A[A == 2])

# 유형 3 : True인 위치를 반환 ([0, 3]행, 2번째 열)
print(A[[True, False, False, True], [False, True]])

# 유형 4 : 쌓는 방법
print(A[torch.tensor([1, 1, 1, 2, 2])])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [3, 4],
        [5, 6],
        [5, 6]])


## pytorch 함수

In [14]:
A = torch.randn(3, 3)  # 정규분포
B = torch.rand(3, 3)  # uniform
print(A)
print(B)
print(A[A[:, 0] < 0, :])  # 0 번째 열이 음수인 행 전부 가져오기

tensor([[ 0.4730, -0.6035,  0.5805],
        [-0.9933,  0.0586,  0.7705],
        [ 0.8630,  1.0854,  1.4971]])
tensor([[0.0089, 0.8637, 0.1702],
        [0.7900, 0.1210, 0.9447],
        [0.8729, 0.9566, 0.8457]])
tensor([[-0.9933,  0.0586,  0.7705]])


In [15]:
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(torch.abs(A)))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1))))  # tensor 형만 인수로 사용할 수 있음 = e^1
print(torch.log10(torch.abs(A)))
print(torch.log2(torch.abs(A)))
print(torch.round(A))
print(torch.round(A, decimals=2))
print(torch.floor(A))  # 내림
print(torch.ceil(A))  # 올림

tensor([[ 0.4730, -0.6035,  0.5805],
        [-0.9933,  0.0586,  0.7705],
        [ 0.8630,  1.0854,  1.4971]])
tensor([[0.4730, 0.6035, 0.5805],
        [0.9933, 0.0586, 0.7705],
        [0.8630, 1.0854, 1.4971]])
tensor([[0.6877, 0.7768, 0.7619],
        [0.9966, 0.2420, 0.8778],
        [0.9290, 1.0418, 1.2236]])
tensor([[1.6047, 1.8284, 1.7869],
        [2.7000, 1.0603, 2.1608],
        [2.3702, 2.9606, 4.4688]])
tensor([[-0.7488, -0.5051, -0.5439],
        [-0.0068, -2.8373, -0.2607],
        [-0.1474,  0.0819,  0.4035]])
tensor(1.)
tensor([[-0.3252, -0.2194, -0.2362],
        [-0.0029, -1.2322, -0.1132],
        [-0.0640,  0.0356,  0.1753]])
tensor([[-1.0802, -0.7287, -0.7847],
        [-0.0098, -4.0933, -0.3762],
        [-0.2126,  0.1182,  0.5822]])
tensor([[ 0., -1.,  1.],
        [-1.,  0.,  1.],
        [ 1.,  1.,  1.]])
tensor([[ 0.4700, -0.6000,  0.5800],
        [-0.9900,  0.0600,  0.7700],
        [ 0.8600,  1.0900,  1.5000]])
tensor([[ 0., -1.,  0.],
        [-1.,  0., 

In [16]:
print(torch.sin(torch.tensor(torch.pi / 6)))
print(torch.cos(torch.tensor(torch.pi / 6)))
print(torch.tan(torch.tensor(torch.pi / 6)))
print(torch.tanh(torch.tensor(torch.pi / 6)))

print(type(torch.pi))
print(type(torch.pi * torch.tensor(3)))  # tensor로 자동 바뀜

tensor(0.5000)
tensor(0.8660)
tensor(0.5774)
tensor(0.4805)
<class 'float'>
<class 'torch.Tensor'>


In [17]:
print(torch.log(torch.tensor(-1)))  # 실수가 아님
print(torch.isnan(torch.tensor([1, 2, torch.nan, 3, 4])))  # not a number
print(torch.isinf(torch.tensor([1, 2, torch.inf, 3, 4])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False,  True, False, False])


In [18]:
A = torch.randn(3, 4)
print(A)
print(torch.max(A))
print(torch.max(A, dim=0))
print(torch.max(A, dim=1))
print(torch.max(A, dim=1, keepdims=True))  # 행렬의 차원을 유지함
print(torch.min(A))
print(torch.min(A, dim=0))
print(torch.min(A, dim=1))
print(torch.argmax(A))
print(torch.argmax(A, dim=0))  # 남는 디멘전으로 생각하면 편할 듯(4개)
print(torch.argmax(A, dim=1))

tensor([[ 0.4885, -0.2673, -1.7764, -1.0192],
        [-0.3780,  0.8515, -0.3869,  0.2123],
        [-1.0265, -1.0657, -0.0038, -1.2318]])
tensor(0.8515)
torch.return_types.max(
values=tensor([ 0.4885,  0.8515, -0.0038,  0.2123]),
indices=tensor([0, 1, 2, 1]))
torch.return_types.max(
values=tensor([ 0.4885,  0.8515, -0.0038]),
indices=tensor([0, 1, 2]))
torch.return_types.max(
values=tensor([[ 0.4885],
        [ 0.8515],
        [-0.0038]]),
indices=tensor([[0],
        [1],
        [2]]))
tensor(-1.7764)
torch.return_types.min(
values=tensor([-1.0265, -1.0657, -1.7764, -1.2318]),
indices=tensor([2, 2, 0, 2]))
torch.return_types.min(
values=tensor([-1.7764, -0.3869, -1.2318]),
indices=tensor([2, 2, 3]))
tensor(5)
tensor([0, 1, 2, 1])
tensor([0, 1, 2])


In [19]:
a = torch.randn(6, 1)
print(a)
a_sorted = torch.sort(a, dim=0)
print(a_sorted)
a_sorted = torch.sort(a, dim=0, descending=True)
print(a_sorted)

tensor([[ 1.1181],
        [ 0.2396],
        [ 0.2433],
        [-0.3141],
        [ 0.0141],
        [-2.2320]])
torch.return_types.sort(
values=tensor([[-2.2320],
        [-0.3141],
        [ 0.0141],
        [ 0.2396],
        [ 0.2433],
        [ 1.1181]]),
indices=tensor([[5],
        [3],
        [4],
        [1],
        [2],
        [0]]))
torch.return_types.sort(
values=tensor([[ 1.1181],
        [ 0.2433],
        [ 0.2396],
        [ 0.0141],
        [-0.3141],
        [-2.2320]]),
indices=tensor([[0],
        [2],
        [1],
        [4],
        [3],
        [5]]))


In [20]:
A = torch.randn(3, 4)
print(A)
print(torch.sum(A))
print(torch.sum(A, dim=1))
print(torch.sum(A, dim=1, keepdims=True))
print(torch.mean(A))
print(torch.mean(A, dim=1))
print(torch.mean(A, dim=1, keepdims=True))
print(torch.std(A))

tensor([[ 0.7012, -0.9653, -1.5544, -0.5260],
        [ 1.0871, -1.4808, -1.9465, -0.5473],
        [ 0.3484,  0.0154, -0.1280, -0.6021]])
tensor(-5.5983)
tensor([-2.3445, -2.8876, -0.3663])
tensor([[-2.3445],
        [-2.8876],
        [-0.3663]])
tensor(-0.4665)
tensor([-0.5861, -0.7219, -0.0916])
tensor([[-0.5861],
        [-0.7219],
        [-0.0916]])
tensor(0.9278)


In [21]:
A = torch.randint(1, 5, size=(12,))
print(A)
print(A.shape)

B = A.reshape(2, 2, 3)
print(B)
print(B.ndim)

tensor([2, 3, 2, 4, 1, 4, 1, 1, 1, 4, 3, 2])
torch.Size([12])
tensor([[[2, 3, 2],
         [4, 1, 4]],

        [[1, 1, 1],
         [4, 3, 2]]])
3


In [22]:
a = torch.tensor([1, 2, 3])  # 1*2 + 2*2 + 3*1
b = torch.tensor([2, 2, 1])
print(torch.sum(a * b))

a = a.reshape(3, 1)
b = b.reshape(3, 1)
print(a.transpose(1, 0) @ b)
print(a.permute(1, 0) @ b)
print(a.T @ b)
print(a.t() @ b)

A = torch.randn(4, 3, 6)
print(A.permute(0, 2, 1).shape)  # 파라미터는 차원을 바꾸고 싶은 순서
print(A.transpose(0, 2).shape)  # permute와 달리 둘만 가능

A = torch.rand

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [23]:
A = torch.arange(20)
print(A)
print(A.reshape(4, 5))
print(A.reshape(4, -1))
print(A.reshape(2, 5, -1).shape)
print(A.reshape(2, -1, 5).shape)
print(A.reshape(1, -1).shape)
print(A.reshape(-1, 1).shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [24]:
x = torch.randn(2, 3, 4, 5, 6)
print(x[1, 2, :, :, :].shape)
print(x[1, 2, ...].shape)

print(x[:, :, :, :, 3].shape)
print(x[..., 3].shape)

print(x[1, :, :, 3, :].shape)
print(x[1, ..., 3, :].shape)

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [25]:
A = torch.ones((3, 4))
B = torch.zeros((3, 4))

print(torch.vstack([A, B]))
print(torch.hstack([A, B]))

print(torch.cat([A, B], dim=0))
print(torch.cat([A, B], dim=1))

A = torch.ones((2, 3, 4))
B = torch.zeros((2, 3, 4))

# 다차원을 고려해서 cat을 추천함
print(torch.cat([A, B], dim=0))
print(torch.cat([A, B], dim=1))
print(torch.cat([A, B], dim=2))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0

In [26]:
A = torch.randn(1, 1, 1, 3, 1, 1, 4, 1)
print(A.shape)
A.squeeze().shape

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])


torch.Size([3, 4])

In [27]:
A = torch.randn(3, 4)

print(A.unsqueeze(dim=0).shape)  # 아래와 동일함
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)

print(A.reshape(1, 3, 4).shape)
print(A.reshape(3, 1, 4).shape)
print(A.reshape(3, 4, 1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [28]:
A = torch.ones(3, 4)
B = torch.zeros(3, 4)

A = A.unsqueeze(dim=0)
B = B.unsqueeze(dim=0)

C = torch.cat([A, B], dim=0)  # 차원을 늘려서 쌓고 싶을 때

print(C)
print(C.shape)  # 1시간 55분까지 완료

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
